name:
    unet_env
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    # TODO pin versions
    - scipy
    - sckit-image
    - imageio
    - pytorch >=1.0
    - torch_resources
